mutation CreateUser @auth(level: USER) {
  user_insert(data: {
    id_expr: "uuidV4()",
    displayName: "New User",
    createdAt_expr: "request.time"
  })
}

query ListProducts @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  products {
    id
    name
    price
    description
  }
}

mutation UpdateProduct($id: UUID!, $name: String, $price: Float) @auth(level: USER) {
  product_update(
    id: $id,
    data: {
      name: $name,
      price: $price
    }
  )
}

query GetReviewsForProduct($productId: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  reviews(where: {productId: {eq: $productId}}) {
    id
    comment
    rating
  }
}