// File generated by FlutterFire CLI.
// ignore_for_file: type=never, unused_import

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz4EfU40riAMXt3sdKFFFq5Lc_X5W6WGQ',
    appId: '1:967872205422:web:b16f6c6b6d6cedc5464c7f',
    messagingSenderId: '967872205422',
    projectId: 'multisales-18e57',
    authDomain: 'multisales-18e57.firebaseapp.com',
    databaseURL: 'https://multisales-18e57-default-rtdb.firebaseio.com',
    storageBucket: 'multisales-18e57.firebasestorage.app',
    measurementId: 'G-3DB4WDLJ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwLLMPdBS6MbYCsOSq1_08zNWfa9qXT8',
    appId: '1:967872205422:android:58aec166cee7050d464c7f',
    messagingSenderId: '967872205422',
    projectId: 'multisales-18e57',
    databaseURL: 'https://multisales-18e57-default-rtdb.firebaseio.com',
    storageBucket: 'multisales-18e57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4EfU40riAMXt3sdKFFFq5Lc_X5W6WGQ',
    appId: '1:967872205422:ios:ad097f3bcad20602464c7f',
    messagingSenderId: '967872205422',
    projectId: 'multisales-18e57',
    authDomain: 'multisales-18e57.firebaseapp.com',
    databaseURL: 'https://multisales-18e57-default-rtdb.firebaseio.com',
    storageBucket: 'multisales-18e57.firebasestorage.app',
    iosBundleId: 'com.example.multisalesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz4EfU40riAMXt3sdKFFFq5Lc_X5W6WGQ',
    appId: '1:967872205422:ios:ad097f3bcad20602464c7f',
    messagingSenderId: '967872205422',
    projectId: 'multisales-18e57',
    authDomain: 'multisales-18e57.firebaseapp.com',
    databaseURL: 'https://multisales-18e57-default-rtdb.firebaseio.com',
    storageBucket: 'multisales-18e57.firebasestorage.app',
    iosBundleId: 'com.example.multisalesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz4EfU40riAMXt3sdKFFFq5Lc_X5W6WGQ',
    appId: '1:967872205422:web:385f9e13dc6def6e464c7f',
    messagingSenderId: '967872205422',
    projectId: 'multisales-18e57',
    authDomain: 'multisales-18e57.firebaseapp.com',
    databaseURL: 'https://multisales-18e57-default-rtdb.firebaseio.com',
    storageBucket: 'multisales-18e57.firebasestorage.app',
    measurementId: 'G-179HV94WC8',
  );
}
